name: release

on:
  release:
    types:
      - created
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.0.1
      - name: Build
        uses: thatisuday/go-cross-build@v1.1.0
        with:
          platforms: 'linux/amd64, darwin/amd64'
          compress: false
          name: matelight-publiccontrol
          dest: dist
          # workaround for bug in go-cross-build
          ldflags: '""' 
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*"
